config:
  backbone:
    ch_in: 1
    n_layers: 4
    init_filters: 8
    ch_out: 8
  encoder:
    ch_in: 8 
    n_ctx: 16
    patch_size: [2,2]

    n_blocks: 4
    n_embd: 192
    n_heads: 4
  decoder:
    n_ctx: 34
    n_vocab: 100
    n_blocks: 4
    n_embd: 192
    n_heads: 4
